{{- if .Values.appconfigs.configmap.enabled }}
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: {{ .Values.configmap.secretname }}
  namespace: {{ .Values.namespace }}
spec:
  provider: gke
  parameters:
    secrets: |
      - resourceName: "projects/alperenokur-sandbox-415013/secrets/{{ .Values.configmap.smname }}/versions/latest"
        path: "{{ .Values.configmap.pathname }}"
{{- end }}